name: "upload hashes"

on:
  workflow_dispatch:
  release:
    types: [created, prereleased]

jobs:
  generate_hashes:
    runs-on: ubuntu-latest
    steps:
      - uses: MCJack123/ghaction-generate-release-hashes@v3
        with:
          get-assets: true
          hash-type: md5
          file-name: hashes.txt
      - uses: actions/upload-artifact@v4
        with:
          name: Asset Hashes
          path: hashes.txt
