name: "publish"

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "ubuntu-22.04"
            args: ""
          - platform: "windows-latest"
            args: ""

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
          libwebkit2gtk-4.0-dev \
          libappindicator3-dev \
          librsvg2-dev \
          patchelf \
          libssl-dev

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - uses: jetli/trunk-action@v0.5.0
        with:
          version: "latest"

      - name: add target
        run: |
          rustup target add wasm32-unknown-unknown

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: "${{  github.ref_name }}"
          releaseName: "PaperSmith ${{  github.ref_name }}"
          releaseBody: "See the assets to download this version and install."
          iconPath: "src-tauri/icons/icon.png"
          appVersion: "${{  github.ref_name }}"
          releaseDraft: false
          prerelease: true
          args: ${{ matrix.args }}

      - name: upload binary
        if: matrix.platform == 'ubuntu-22.04'
        uses: djnicholson/release-action@v2.10
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          asset-name: "papersmith-portable"
          file: "target/release/paper-smith"
          release-name: "PaperSmith ${{  github.ref_name }}"
          tag-name: "${{  github.ref_name }}"
